[2022-03-01 20:11:10,622] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_flights.read_process_write_file manual__2022-03-01T20:10:48+00:00 [queued]>
[2022-03-01 20:11:10,633] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_flights.read_process_write_file manual__2022-03-01T20:10:48+00:00 [queued]>
[2022-03-01 20:11:10,633] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-01 20:11:10,633] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-01 20:11:10,633] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-01 20:11:10,650] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): read_process_write_file> on 2022-03-01 20:10:48+00:00
[2022-03-01 20:11:10,654] {standard_task_runner.py:52} INFO - Started process 4314 to run task
[2022-03-01 20:11:10,658] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_flights', 'read_process_write_file', 'manual__2022-03-01T20:10:48+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag_flights.py', '--cfg-path', '/tmp/tmpjva9uoqw', '--error-file', '/tmp/tmptya2toyq']
[2022-03-01 20:11:10,658] {standard_task_runner.py:77} INFO - Job 53: Subtask read_process_write_file
[2022-03-01 20:11:10,719] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_flights.read_process_write_file manual__2022-03-01T20:10:48+00:00 [running]> on host 083589a500f4
[2022-03-01 20:11:10,756] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/xcom.py:437: SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  return query.delete()

[2022-03-01 20:11:10,769] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:126: SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  session.merge(self)

[2022-03-01 20:11:10,778] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:162: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
  tuple_(cls.dag_id, cls.task_id, cls.execution_date).notin_(subq1),

[2022-03-01 20:11:10,784] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:163: SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ).delete(synchronize_session=False)

[2022-03-01 20:11:10,789] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_flights
AIRFLOW_CTX_TASK_ID=read_process_write_file
AIRFLOW_CTX_EXECUTION_DATE=2022-03-01T20:10:48+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-01T20:10:48+00:00
[2022-03-01 20:11:11,594] {__init__.py:490} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-0qz4gdbv because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-03-01 20:11:11,873] {font_manager.py:1443} INFO - generated new fontManager
[2022-03-01 20:11:13,972] {logging_mixin.py:109} INFO - read success
[2022-03-01 20:11:14,253] {category.py:234} INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
[2022-03-01 20:11:14,254] {category.py:234} INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
[2022-03-01 20:11:14,329] {category.py:234} INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
[2022-03-01 20:11:14,330] {category.py:234} INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
[2022-03-01 20:11:15,604] {python.py:175} INFO - Done. Returned value was: None
[2022-03-01 20:11:15,620] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=dag_flights, task_id=read_process_write_file, execution_date=20220301T201048, start_date=20220301T201110, end_date=20220301T201115
[2022-03-01 20:11:15,660] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-01 20:11:15,679] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dag.py:1079: SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
  return qry.value(DagModel.is_paused)

[2022-03-01 20:11:15,679] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dag.py:1079: SADeprecationWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)
  return qry.value(DagModel.is_paused)

